name: Auto-update GitHub Snake

on:
  # запуск при пуше в основную ветку, но изменения только внутри dist-папки не триггерят повторно
  push:
    branches: [main]
    paths-ignore:
      - 'svg-only/dist/**'

  # ежедневный запуск в 00:00 UTC
  schedule:
    - cron: '0 0 * * *'

  # ручной запуск кнопкой «Run workflow»
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      # 1 — клонируем репозиторий
      - uses: actions/checkout@v3

      # 2 — генерируем SVG-файлы («светлый» и «тёмный» варианты)
      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            svg-only/dist/github-contribution-grid-snake.svg
            svg-only/dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 3 — коммитим изменения, только если файлы реально изменились
      - name: Commit & push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add svg-only/dist/*.svg

          # коммитим, только если есть изменения
          if git diff --cached --quiet; then
            echo "Nothing to commit"
          else
            git commit -m "ci: update contribution snake"
            git push
          fi
